stages:
  - lint
  - test
  - tag
  - build
  - deploy
  - mirror

include:
  - project: 'internal/ci-templates'
    ref: main
    file: 'npm-lint.yml'
  - project: 'internal/ci-templates'
    ref: main
    file: 'npm-test.yml'
  - project: 'internal/ci-templates'
    ref: main
    file: 'npm-tag.yml'
  - project: 'internal/ci-templates'
    ref: main
    file: 'npm-build-arm.yml'
  - project: 'internal/ci-templates'
    ref: main
    file: 'npm-deploy.yml'
  - project: 'internal/ci-templates'
    ref: main
    file: 'mirror-to-github.yml'

variables:
  IMAGE_NAME: registry.yauseyenka.de/internal/micro-services/matrix-bot
  HTTPS_REPO: github.com/yauseyea/matrix-bot.git

